#!/bin/sh
TIMESTAMP=$(date +%s000)
VALUE=${1:-1.0}
UNIT=${2:-PPM}
LABEL=${3:-Leakage}

mosquitto_pub \
	--cert $HOME/.agent/certs/$DEVICE_ID.cert.pem \
	--key $HOME/.agent/certs/$DEVICE_ID.private.key \
	--cafile $HOME/.agent/certs/root-CA.crt \
	-h $AWS_IOT_ADDRESS -p 8883 -t 'telemetry/sensors' \
	-m '{"unit": "'${UNIT}'", "temperature": 25.5, "ownerID": "'${DEVICE_OWNER}'", "@timestamp": '${TIMESTAMP}', "humidity": 68.8, "ID": "'${DEVICE_ID}'", "value": '${VALUE}', "label": "'${LABEL}'"}'
