#!/bin/sh
#https://api.mylnikov.org/wifi?v=1.1&bssid=F0:5C:19:31:84:E0
if [ -f /tmp/last-bssid ]; then
    LAST_BSSID=$(cat /tmp/last-bssid)
fi
LINK=$(iwinfo wlan0 info | awk 'NR==2 {print $3}')
SCAN_RESULT=$(iwinfo wlan0 scan)
LOOP_COUNT=1
SIGNAL=-99
NAME="00:00:00:00"
while [[ ! "$NAME" == "" ]]
do
    SHIFT_COUNT=$((LOOP_COUNT+3))
    VALUE=$(echo "$SCAN_RESULT" | awk 'NR=='$SHIFT_COUNT' {print $2}')
    NAME=$(echo "$SCAN_RESULT" | awk 'NR=='$LOOP_COUNT' {print $5}')
    LABEL=$(echo "$SCAN_RESULT" | awk 'NR=='$((LOOP_COUNT+1))' {$1=""; print $0}')
    LOOP_COUNT=$((SHIFT_COUNT+3))
    if [[ "$VALUE" == "" ]]; then
        VALUE=-99
    fi
    if [[ $(( VALUE > SIGNAL )) -ne 0 ]] && [[ ! "$BSSID" == "$LINK" ]]
    then
            SIGNAL=$VALUE
            BSSID=$NAME
            ESSID=$LABEL
    fi        
done
if [[ ! "$LAST_BSSID" == "$BSSID" ]] && [[ ! "$BSSID" == "$LINK" ]]
then
    echo "$BSSID" > /tmp/last-bssid
    TIMESTAMP=$(date +%s000)
    echo "$TIMESTAMP $BSSID $SIGNAL" >> /tmp/data    
fi
