#!/bin/sh
NUM_OF_SAMPLES=0
LINK=$(iwinfo wlan0 info | awk 'NR==2 {print $3}')
if [[ ! "$LINK" == "" ]]
then
    while read -r line
    do
        if [[ ! "$line" == "" ]]
        then
            TIMESTAMP=$(echo $line | awk 'NR==1 {print $1}')
            BSSID=$(echo $line | awk 'NR==1 {print $2}')
            SIGNAL=$(echo $line | awk 'NR==1 {print $3}')
            mosquitto_pub \
                --cert $HOME/.agent/certs/$DEVICE_ID.cert.pem \
                --key $HOME/.agent/certs/$DEVICE_ID.private.key \
                --cafile $HOME/.agent/certs/root-CA.crt \
                -h $AWS_IOT_ADDRESS -p 8883 -t 'tracking/proximity' \
                -m '{"@timestamp": '${TIMESTAMP}', "ID": "'${DEVICE_ID}'", "ownerID": "'${DEVICE_OWNER}'", "signal": '${SIGNAL}', "bssid":"'${BSSID}'"}'
        fi
        NUM_OF_SAMPLES=$((NUM_OF_SAMPLES+1))
        if [[ $(( NUM_OF_SAMPLES < 30 )) -ne 0 ]]
        then
            sleep 1
        else
            break
        fi
    done < /tmp/data-proximity
    sed -i "1,$NUM_OF_SAMPLES d" /tmp/data-proximity
fi
