#!/bin/sh
export PYTHONIOENCODING=utf8
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[1;30m' # No Color
DEF='\033[0m' # Default Color

LOCK_STATE=$HOME/.agent/.lock-state
if [ -f $LOCK_STATE ];
then
   	echo -e "${BLUE}INFO: The device ${DEVICE_ID} has already installed successfully.${NC}"
else	
	echo -e "${BLUE}INFO: Activating the device ${DEVICE_ID}${NC}"
	DEVICE_OBJECT=$(curl -H "Content-Type: application/json" -L ${SERVICE_ENDPOINT}/apisrv/device-lifecycle-service/device/${DEVICE_ID}?secret_key=${SECRET_KEY})
	DEVICE_OWNER=$(echo ${DEVICE_OBJECT} | python -c "import sys, json; print json.load(sys.stdin)['owner']" 2> /dev/null)
	DEVICE_STATUS=$(echo ${DEVICE_OBJECT} | python -c "import sys, json; print json.load(sys.stdin)['status']" 2> /dev/null)
	SERIAL_NUMBER=$(echo ${DEVICE_OBJECT} | python -c "import sys, json; print json.load(sys.stdin)['_metadata']['serialNumber']" 2> /dev/null)	
	
	if [ "${DEVICE_STATUS}" = "unregistered" ]; then
		PAYLOAD=$(curl -H "Content-Type: application/json" -X POST -d '{"name":"'"${DEVICE_ID}"'","serialNumber":"'"${SERIAL_NUMBER}"'","status":"'"${DEVICE_STATUS}"'"}' -L ${SERVICE_ENDPOINT}/apisrv/device-lifecycle-service/lifecycle/initialization?secret_key=${SECRET_KEY})	
		PINCODE=$(echo ${PAYLOAD} | python -c "import sys, json; print json.load(sys.stdin)['pincode']" 2> /dev/null)		
		if [ "${INSTALL_ALL}" = "YES" ]; then
			echo -e "${BLUE}INFO: Registering the device with PINCODE:${PINCODE}${NC}"
			citus-device register ${PINCODE}
		else
			echo -e "${GREEN}========================="
			echo -e "| ACTIVATION CODE: ${PINCODE} |"
			echo -e "=========================${NC}"
		fi
	elif [ "${DEVICE_STATUS}" = "registered" ]; then
		echo -e "${YELLOW}WARN: The device ${DEVICE_ID} has already used on another device! Please pickup another one and try again.${NC}"
	else
		echo -e "${RED}ERROR: ${DEVICE_OBJECT}${NC}"
	fi
fi
echo -e "${DEF}"