#!/bin/sh
export PYTHONIOENCODING=utf8
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[1;30m' # No Color
DEF='\033[0m' # Default Color

LOCK_STATE=$HOME/.agent/.lock-state
if [ -f $LOCK_STATE ];
then
   	echo -e "${BLUE}INFO: The device ${DEVICE_ID} has already installed successfully.${NC}"
else	
	echo -e "${BLUE}INFO: Get device info: ${DEVICE_ID}${NC}"
	DEVICE_OBJECT=$(curl -H "Content-Type: application/json" -L ${SERVICE_ENDPOINT}/apisrv/device-management-service/device/${DEVICE_ID}?secret_key=${SECRET_KEY})
	DEVICE_OWNER=$(echo ${DEVICE_OBJECT} | python -c "import sys, json; print json.load(sys.stdin)['owner']" 2> /dev/null)
	DEVICE_STATUS=$(echo ${DEVICE_OBJECT} | python -c "import sys, json; print json.load(sys.stdin)['status']" 2> /dev/null)
	SERIAL_NUMBER=$(echo ${DEVICE_OBJECT} | python -c "import sys, json; print json.load(sys.stdin)['_metadata']['serialNumber']" 2> /dev/null)	
	
	/usr/local/bin/gateway ${DEVICE_ID} ${DEVICE_OWNER} ${DEVICE_STATUS} ${SERIAL_NUMBER} ${SECRET_KEY}
fi
echo -e "${DEF}"