#!/bin/bash
echo "Installing NodeJS 6.x..."
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt install -y nodejs
echo "Installing Citus IoT Device SDK..."
https://github.com/cuongquay/citus-iot-sdk-nodejs.git $HOME/citus-iot-sdk-nodejs/
cd $HOME/citus-iot-sdk-nodejs/ && npm install && npm update
echo "Try it out! Type 'npm run examples' on the console."
cd $HOME; rm -rf $HOME/citus-iot-sdk-nodejs/
echo "==============================="
echo "| Installed SDK successfully! |"
echo "==============================="
echo "Try 'npm install' to build the sdk."