#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -e "INFO: Installing NodeJS 6.x..."
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt install -y nodejs
echo -e "INFO: Installing Citus IoT Device SDK..."
https://github.com/cuongquay/citus-iot-sdk-nodejs.git $HOME/citus-iot-sdk-nodejs/
cd $HOME/citus-iot-sdk-nodejs/ && npm install && npm update
echo -e "${GREEN}==============================="
echo -e "| Installed SDK successfully! |"
echo -e "===============================${NC}"
echo -e "INFO: Try 'npm run test' to test your connection."