#!/bin/sh
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[1;30m' # No Color
DEF='\033[0m' # Default Color

ACCESS_TOKEN=${1:-Unknown}
CERTIFICATE_ID=${2:-Unknown}
CERTS_STATE=$HOME/.agent/certs
DEVICE_OWNER=${3:-Unknown}

if [ -f $CERTS_STATE ];
then
   	echo -e "${BLUE}INFO: The certificates of device ${DEVICE_ID} has already installed successfully.${NC}"
else
	mkdir -p $HOME/.agent/certs/
	curl -o "$HOME/.agent/certs/root-CA.crt" https://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem
	
	python /usr/sbin/citus/getcert.py ${CERTIFICATE_ID} ${ACCESS_TOKEN}
	
	echo -e "${GREEN}INFO: Update Device Metadata Infor:${NC}"
	
	python /usr/sbin/citus/setinfo.py ${DEVICE_OWNER}
	
	echo -e "${GREEN}INFO: Installed Certificates:${NC}"
	ls -td $(find $HOME/.agent/certs/)
	(echo "* * * * * /usr/sbin/citus-device update >$HOME/.agent/update.log ") | crontab -
fi
echo -e "${DEF}"