#!/bin/sh
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[1;30m' # No Color
DEF='\033[0m' # Default Color
DEVICE_NAME="FPT-"$(hostname)
PINCODE=${1:-Unknown}
TIMESTAMP=$(date +%s000)

LOCK_STATE=$HOME/.agent/.lock-state
if [ -f $LOCK_STATE ];
then
   	echo -e "${BLUE}INFO: The device ${DEVICE_ID} has already installed successfully.${NC}"
else	
	DEVICE_OBJECT=$(curl -H "Content-Type: application/json" -L ${SERVICE_ENDPOINT}/apisrv/device-management-service/device/${DEVICE_ID}?secret_key=${SECRET_KEY})
	DEVICE_OWNER=$(echo ${DEVICE_OBJECT} | python -c "import sys, json; print json.load(sys.stdin)['owner']" 2> /dev/null)
	DEVICE_STATUS=$(echo ${DEVICE_OBJECT} | python -c "import sys, json; print json.load(sys.stdin)['status']" 2> /dev/null)
	SERIAL_NUMBER=$(echo ${DEVICE_OBJECT} | python -c "import sys, json; print json.load(sys.stdin)['_metadata']['serialNumber']" 2> /dev/null)	
	
	if [ "${DEVICE_STATUS}" = "unregistered" ]; then		
		mkdir -p $HOME/.agent/certs/
		curl -o "$HOME/.agent/certs/root-CA.crt" https://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem
		echo "${DEVICE_OWNER}" > ${OWNER_STATE}
		
		RESULT=$(python /usr/sbin/citus/register.py '{"name":"'"${DEVICE_ID}"'","serialNumber":"'"${SERIAL_NUMBER}"'","status":"'"${DEVICE_STATUS}"'","pincode":"'"${PINCODE}"'"}')
				
		if [ "${RESULT}" = "registered" ]; then
			echo "${RESULT}" > ${LOCK_STATE}
			echo -e "${BLUE}INFO: Device Status - ${RESULT}${NC}"
			
			python /usr/sbin/citus/setinfo.py ${DEVICE_OWNER}
			
			echo -e "${YELLOW}INFO: Installed Certificates:${NC}"
			ls -td $(find $HOME/.agent/certs/)
			(echo "* * * * * /usr/sbin/citus-device update >$HOME/.agent/update.log ") | crontab -
		else
			echo -e "${RED}ERROR: Your device is not activated successfully!${NC}"
		fi
	elif [ "${DEVICE_STATUS}" = "registered" ]; then
		echo -e "${YELLOW}WARN: The device ${DEVICE_ID} has already used on another device! Please pickup another one and try again.${NC}"
	else
		echo -e "${RED}ERROR: ${DEVICE_OBJECT}${NC}"
	fi
fi
echo -e "${DEF}"