#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
export PYTHONIOENCODING=utf8
LOCK_STATE=$HOME/.agent/.lock-state
if [ -f $LOCK_STATE ];
then
   	echo "Removing device ${DEVICE_ID}..."
   	citus-device revoke
   	rm -rf $HOME/.agent/   	
   	echo "${GREEN}============================="
   	echo "| The Device is CLEANED UP. |"
   	echo "=============================${NC}"
else
	echo "This device is not installed yet."
fi
