#!/bin/sh
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[1;30m' # No Color
DEF='\033[0m' # Default Color

LOCK_STATE=$HOME/.agent/.lock-state
if [ -f $LOCK_STATE ];
then   	
	echo -e "INFO: Deactivating the device ${DEVICE_ID}"
	DEVICE_OBJECT=$(curl -H "Content-Type: application/json" -L ${SERVICE_ENDPOINT}/apisrv/device-lifecycle-service/device/${DEVICE_ID}?secret_key=${SECRET_KEY})
	
	DEVICE_STATUS=$(echo ${DEVICE_OBJECT} | python -c "import sys, json; print json.load(sys.stdin)['status']" 2> /dev/null)
	SERIAL_NUMBER=$(echo ${DEVICE_OBJECT} | python -c "import sys, json; print json.load(sys.stdin)['_metadata']['serialNumber']" 2> /dev/null)
	
	if [ "${DEVICE_STATUS}" == "registered" ]; then
		PAYLOAD=$(curl -H "Content-Type: application/json" -X POST -d '{"name":"'"${DEVICE_ID}"'","serialNumber":"'"${SERIAL_NUMBER}"'","status":"'"${DEVICE_STATUS}"'"}' -L ${SERVICE_ENDPOINT}/apisrv/device-lifecycle-service/lifecycle/revocation?secret_key=${SECRET_KEY})		
		NEW_STATUS=$(echo ${PAYLOAD} | python -c "import sys, json; print json.load(sys.stdin)['status']" 2> /dev/null)
		echo "${NEW_STATUS}" >> ${LOCK_STATE}
		echo -e "${BLUE}INFO: Device Status - ${NEW_STATUS}${NC}"		
	else		
		echo -e "${RED}ERROR: The device ${DEVICE_ID} has already used on another device! Please pickup another one and try again.${NC}"
	fi
fi
echo -e "${DEF}"
