#!/bin/sh
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[1;30m' # No Color
DEF='\033[0m' # Default Color

export PYTHONIOENCODING=utf8
LOCK_STATE=$HOME/.agent/.lock-state
if [ -f $LOCK_STATE ];
then
	echo -e "${BLUE}INFO: Checking for Software Update - ID:${DEVICE_ID}${NC}"
	DEVICE_OBJECT=$(curl -H "Content-Type: application/json" -L ${SERVICE_ENDPOINT}/apisrv/device-lifecycle-service/device/${DEVICE_ID}?secret_key=${SECRET_KEY})	
	
	SERIAL_NUMBER=$(echo ${DEVICE_OBJECT} | python -c "import sys, json; print json.load(sys.stdin)['_metadata']['serialNumber']" 2> /dev/null)
	DEVICE_OWNER=$(echo ${DEVICE_OBJECT} | python -c "import sys, json; print json.load(sys.stdin)['owner']" 2> /dev/null)
	SOFTWARE_SCRIPT=$(echo ${DEVICE_OBJECT} | python -c "import sys, json; print json.load(sys.stdin)['_metadata']['software']" 2> /dev/null)
	HAS_UPDATED=$(echo ${DEVICE_OBJECT} | python -c "import sys, json; print json.load(sys.stdin)['_metadata']['updated']" 2> /dev/null)	
	SELF_UPDATE=$(echo ${DEVICE_OBJECT} | python -c "import sys, json; print json.load(sys.stdin)['_metadata']['selfUpdate']" 2> /dev/null)
	
	if [ "${SELF_UPDATE}" == "False" ]; then
		echo -e "${BLUE}INFO: Self Software Update feature is disabled${NC}"
	else
		echo -e "${BLUE}INFO: Software Update Status: ${SERIAL_NUMBER} - ${HAS_UPDATED}.${NC}"
		if [ "${HAS_UPDATED}" == "False" ]; then
			echo -e "${YELLOW}INFO: Executing software script: ${SOFTWARE_SCRIPT}${NC}"
			sh -c "${SOFTWARE_SCRIPT}" | tee ; ( exit ${PIPESTATUS} ); 
			RETCODE=$(echo "$?")
			if [ "${RETCODE}" == 0 ]; then
				RESULT=$(curl -H "Content-Type: application/json" -X PUT -d '{"name":"'"${DEVICE_ID}"'","owner":"'"${DEVICE_OWNER}"'","_metadata":{"updated":true}}' -L ${SERVICE_ENDPOINT}/apisrv/device-lifecycle-service/device/${DEVICE_ID}/_metadata?secret_key=${SECRET_KEY})
				echo -e "INFO: ${RESULT}"
				echo -e "${GREEN}INFO: The device ${DEVICE_ID} is up-to-date.${NC}"
			else
				echo -e "${RED}ERROR: Can't update this device due to an unexpected error.${NC}"
			fi
		else
			echo -e "${GREEN}INFO: The software ${SERIAL_NUMBER} has already updated yet.${NC}"	
		fi
	fi
else
	echo -e "${YELLOW}WARN: The device ${DEVICE_ID} is not activated yet.${NC}"	
fi	
echo -e "${DEF}"